version: "3"
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd [プロジェクト名] && npm run dev"
    ports:
      - "3000:3000"
